apiVersion: v1
kind: ConfigMap
metadata:
  name: common
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/common.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-create
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/volumes-create.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-delete
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/volumes-delete.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-map
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/volumes-map.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powermax-volumes-create
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/volumes-powermax-create.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerscale-volumes-create
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/volumes-powerscale-create.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-unmap
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "policies/volumes-unmap.rego").AsConfig | nindent 2 }}